<?php

namespace App\Http\Controllers\Admin;

use App\Exports\MockSessionsExport;
use App\Http\Controllers\Controller;
use App\Models\mocks;
use App\Models\mock_Schedules;
use App\Models\mock_sessions;
use App\Models\mock_sessionsSession;
use App\Repositories\MockRepository;
use App\Settings\LocalizationSettings;
use App\Settings\SiteSettings;
use App\Transformers\Admin\MockScoreReportTransformer;
use App\Transformers\Admin\MockSessionExportTransformer;
use App\Transformers\Admin\UserMockSessionTransformer;
use App\Transformers\Platform\QuizSolutionTransformer;
use Barryvdh\DomPDF\Facade as PDF;
use Carbon\Carbon;
use Inertia\Inertia;
use Maatwebsite\Excel\Facades\Excel;

class MockAnalyticsController extends Controller
{
    /**
     * @var MockRepository
     */
    private MockRepository $repository;

    public function __construct(MockRepository $repository)
    {
        $this->middleware(['role:admin|instructor|parent']);
        $this->repository = $repository;
    }

    /**
     * Get mock Overall Report with statistics from sessions
     *
     * @param mocks $mock
     * @return \Inertia\Response
     */
    public function overallReport(mocks $mock)
    {
        // dd($mock);
        $schedule = null;

        if(request()->has('schedule')) {
            $schedule = mock_Schedules::where('id', '=', request()->get('schedule'))->first();
            $stats = $this->repository->getMockSessionStats($mock->id, request()->get('schedule'));
        } else {
            $stats = $this->repository->getMockSessionStats($mock->id, null);
        }

        return Inertia::render('Parent/Mock/OverallReport', [
            'mock' => $mock->only('id', 'code', 'title', 'slug'),
            'schedule' => $schedule != null ? $schedule->only('id', 'code') : null,
            'stats' => [
                'total_attempts' => $stats[0]->total_attempts,
                'pass_count' => $stats[0]->pass_count,
                'failed_count' => $stats[0]->failed_count,
                'unique_test_takers' => $stats[0]->unique_test_takers,
                'avg_time' => formattedSeconds(round($stats[0]->avg_time, 0)),
                'avg_score' => round($stats[0]->avg_score, 1).'/'.$mock->total_marks,
                'high_score' => round($stats[0]->high_score, 1),
                'low_score' => round($stats[0]->low_score, 1),
                'avg_percentage' => round($stats[0]->avg_percentage, 0)."%",
                'avg_accuracy' => round($stats[0]->avg_accuracy, 0)."%",
                'avg_speed' => round($stats[0]->avg_speed, 0)." que/hr",
                'avg_questions_answered' => round(calculatePercentage($stats[0]->sum_answered, $stats[0]->sum_questions), 0)."%",
            ],
        ]);
    }

    /**
     * Get mock Detailed Report with user sessions
     *
     * @param mocks $mock
     * @return \Inertia\Response
     */
    public function detailedReport(mocks $mock)
    {
        $schedule = null;
        if(request()->has('schedule')) {
            $schedule = mock_Schedules::where('id', '=', request()->get('schedule'))->first();
        }

        $key = request()->has('schedule') ? 'mock_schedule_id' : 'mock_id';
        $value = request()->has('schedule') ? request()->get('schedule') : $mock->id;

        $sessions = mock_sessions::with('user:id,first_name,last_name,email')
            ->where($key, '=', $value)
            ->where('status', '=', 'completed')
            ->orderBy('completed_at', 'desc')
            ->paginate(request()->perPage != null ? request()->perPage : 20);

        return Inertia::render('Admin/Mock/DetailedReport', [
            'schedule' => $schedule != null ? $schedule->only('id', 'code') : null,
            'mock' => $mock->only('id', 'code', 'title', 'slug'),
            'mockSessions' => fractal($sessions, new UserMockSessionTransformer($mock))->toArray(),
        ]);
    }

    /**
     * Export mock Report in Excel
     *
     * @param mocks $mock
     * @param LocalizationSettings $localization
     * @param SiteSettings $settings
     * @return \Symfony\Component\HttpFoundation\BinaryFileResponse
     */
    public function exportReport(mocks $mock, LocalizationSettings $localization, SiteSettings $settings)
    {
        $now = Carbon::now()->timezone($localization->default_timezone);
        $user = auth()->user();
        $footer = "Generated by {$user->first_name} {$user->last_name} on {$now->toDayDateTimeString()}";

        if(request()->has('schedule')) {
            $schedule = mock_Schedules::where('id', '=', request()->get('schedule'))->first();
            $stats = $this->repository->getMockSessionStats($mock->id, request()->get('schedule'));
            $title = "{$mock->title} - Schedule ({$schedule->code}) Detailed Report, {$settings->app_name}";
        } else {
            $stats = $this->repository->getMockSessionStats($mock->id, null);
            $title = "{$mock->title} - Detailed Report, {$settings->app_name}";
        }

        $key = request()->has('schedule') ? 'mock_schedule_id' : 'mock_id';
        $value = request()->has('schedule') ? request()->get('schedule') : $mock->id;

        $sessions = fractal(mock_sessions::with('user:id,first_name,last_name,email')
            ->where($key, '=', $value)
            ->where('status', '=', 'completed')
            ->orderBy('completed_at', 'desc')
            ->get(), new MockSessionExportTransformer())->toArray()['data'];

        return Excel::download(new MockSessionsExport($stats[0], $sessions, $title, $footer), "mock-detailed-report-{$now->timestamp}.xlsx");
    }

    /**
     * User mock Session Export PDF
     *
     * @param mocks $mock
     * @param $session
     * @param LocalizationSettings $localization
     * @param SiteSettings $settings
     * @return \Illuminate\Http\Response
     */
    public function exportPDF(mocks $mock, $session, LocalizationSettings $localization, SiteSettings $settings)
    {
        $session = mock_sessions::with('user')->where('code', $session)->firstOrFail();

        $now = Carbon::now()->timezone($localization->default_timezone);
        $user = auth()->user()->first_name.' '.auth()->user()->last_name;

        $pdf = PDF::loadView('pdf.mock-session-report', [
            'mock' => $mock->only('code', 'title'),
            'session' => fractal($session, new MockScoreReportTransformer())->toArray()['data'],
            'footer' => "* Report Generated from {$settings->app_name} by {$user} on {$now->toDayDateTimeString()}",
            'logo' => url('storage/'.$settings->logo_path),
			'rtl' => $localization->default_direction == 'rtl'
        ]);

        return $pdf->download("report-{$session->code}.pdf");
    }

    /**
     * mock Session Analysis and Progress Status
     *
     * @param mocks $mock
     * @param $session
     * @return \Inertia\Response
     */
    public function results(mocks $mock, $session)
    {
        $session = mock_sessions::with('user')->where('code', $session)->firstOrFail();

        return Inertia::render('Admin/mock/SessionResults', [
            'mock' => $mock->only('code', 'title', 'slug', 'total_questions', 'total_marks', 'settings'),
            'session' => fractal($session, new UserMockSessionTransformer($mock))->toArray()['data'],
        ]);
    }

    /**
     * Get mock solutions api endpoint
     *
     * @param mocks $mock
     * @param $session
     * @return \Illuminate\Http\JsonResponse
     */
    public function solutions(mocks $mock, $session)
    {
        $session = mock_sessions::where('code', $session)->firstOrFail();

        $questions = fractal($session->questions()->with(['questionType:id,name,code', 'skill:id,name'])
            ->get(['id','code', 'question', 'question_type_id', 'skill_id', 'solution', 'solution_video']),
            new QuizSolutionTransformer())->toArray();

        return response()->json([
            'questions' => $questions['data'],
        ], 200);
    }
}
